# Generated by Django 4.2.7 on 2025-12-18 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('symbol', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(help_text='Overall edge weight')),
                ('factors_json', models.JSONField(default=dict, help_text='Breakdown of factors (intent, taste, context, etc.)')),
                ('matrix_json', models.JSONField(default=list, help_text='3x3 matrix representation of edge factors')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='api.company')),
                ('target_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='api.company')),
            ],
            options={
                'ordering': ['-weight'],
                'unique_together': {('source_company', 'target_company')},
            },
        ),
        migrations.CreateModel(
            name='CompanyMetricPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('metric_name', models.CharField(choices=[('foot_traffic', 'Foot Traffic'), ('revenue', 'Revenue'), ('intent_index', 'Intent Index'), ('taste_index', 'Taste Index'), ('sentiment_proxy', 'Sentiment Proxy')], max_length=50)),
                ('value', models.FloatField()),
                ('segment_json', models.JSONField(default=dict, help_text='Demographic segment data')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='api.company')),
            ],
            options={
                'ordering': ['-date', 'metric_name'],
                'indexes': [models.Index(fields=['company', 'date', 'metric_name'], name='api_company_company_d4cde1_idx')],
                'unique_together': {('company', 'date', 'metric_name')},
            },
        ),
    ]
