# Generated by Django 4.2.7 on 2025-12-31 22:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_evidencesurveydatum_hypothesisrun_personaagent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalPersona',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('persona_type', models.CharField(choices=[('consumer_insights_head', 'Head of Consumer Insights'), ('regulatory_affairs', 'Regulatory Affairs Manager'), ('brand_manager', 'Brand Manager'), ('finance_forecasting', 'Finance / Forecasting'), ('r_d_director', 'R&D Director'), ('marketing_director', 'Marketing Director')], max_length=50)),
                ('name', models.CharField(help_text='Custom name for this persona', max_length=100)),
                ('taste_acceptance_threshold', models.FloatField(default=0.6, help_text='Minimum taste acceptance rate')),
                ('price_sensitivity_threshold', models.FloatField(default=0.5, help_text='Max acceptable price sensitivity impact')),
                ('health_acceptance_threshold', models.FloatField(default=0.5, help_text='Min health score acceptance')),
                ('cannibalization_risk_threshold', models.FloatField(default=0.3, help_text='Max acceptable cannibalization')),
                ('demographic_coverage_threshold', models.FloatField(default=0.5, help_text='Min demographic acceptance')),
                ('substitution_risk_threshold', models.FloatField(default=0.4, help_text='Max acceptable substitution risk')),
                ('risk_tolerance', models.FloatField(default=0.5)),
                ('factor_weights_json', models.JSONField(default=dict, help_text="Weights for different factors: {'taste': 0.3, 'price': 0.2, 'health': 0.25, ...}")),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['persona_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Human-readable name for this variant', max_length=200)),
                ('base_product_id', models.CharField(help_text='ID of the base product being modified', max_length=100)),
                ('base_product_name', models.CharField(blank=True, max_length=200)),
                ('ingredient_changes_json', models.JSONField(default=dict, help_text="{'added': [list], 'removed': [list], 'substituted': {old: new}}")),
                ('nutrition_delta_json', models.JSONField(default=dict, help_text="{'calories': delta, 'sugar': delta, 'fat': delta, 'sodium': delta, 'protein': delta}")),
                ('sensory_delta_json', models.JSONField(default=dict, help_text="{'sweetness': delta, 'saltiness': delta, 'texture': delta, 'heat': delta, 'aroma': delta}")),
                ('price_delta', models.FloatField(default=0.0, help_text='Price change in dollars')),
                ('positioning_tags_json', models.JSONField(default=list, help_text="Tags like 'healthy', 'indulgent', 'premium', 'value', 'spicy', etc.")),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_count', models.IntegerField(default=1000, help_text='Number of agents in simulation')),
                ('time_horizon_weeks', models.IntegerField(default=12, help_text='Simulation duration in weeks')),
                ('segment_filters_json', models.JSONField(default=dict, help_text="Filters for agent segments: {'age_bucket': [...], 'region': [...], 'archetype': [...]}")),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('results_json', models.JSONField(default=dict, help_text='Simulation results: acceptance rates, preference deltas, entropy metrics, etc.')),
                ('baseline_entropy', models.FloatField(blank=True, null=True)),
                ('post_change_entropy', models.FloatField(blank=True, null=True)),
                ('entropy_delta', models.FloatField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('approval_assessment_json', models.JSONField(default=dict, help_text="Approval assessment by persona: {'persona_id': {'approved': bool, 'reason': str, ...}}")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('recipe_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_runs', to='api.recipevariant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyntheticSurvey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('questions_json', models.JSONField(default=list, help_text='List of questions and response distributions')),
                ('segment_breakdown_json', models.JSONField(default=dict, help_text='Responses broken down by segment')),
                ('summary_stats_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('simulation_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='api.simulationrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyntheticFocusGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('segment_composition_json', models.JSONField(default=dict, help_text='Demographics of focus group participants')),
                ('transcript_json', models.JSONField(default=list, help_text="List of {'speaker': str, 'archetype': str, 'text': str, 'sentiment': float}")),
                ('summary', models.TextField(blank=True)),
                ('key_themes_json', models.JSONField(default=list)),
                ('overall_sentiment', models.FloatField(default=0.5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('simulation_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_groups', to='api.simulationrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LaunchReadinessReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('executive_summary', models.TextField()),
                ('what_changed', models.TextField()),
                ('who_liked_json', models.JSONField(default=dict, help_text='Segments that liked the change')),
                ('who_disliked_json', models.JSONField(default=dict, help_text='Segments that disliked the change')),
                ('risks_json', models.JSONField(default=list, help_text='List of identified risks')),
                ('confidence_score', models.FloatField()),
                ('recommendation', models.CharField(choices=[('proceed', 'Proceed'), ('iterate', 'Iterate'), ('kill', 'Kill')], max_length=20)),
                ('recommendation_reasoning', models.TextField()),
                ('charts_data_json', models.JSONField(default=dict, help_text='Chart data for visualization')),
                ('persona_assessments_json', models.JSONField(default=dict, help_text='Assessments by approval personas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('simulation_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='readiness_report', to='api.simulationrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
