# Generated by Django 4.2.7 on 2025-12-31 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_approvalpersona_recipevariant_simulationrun_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationrun',
            name='metadata_json',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata: simulator_type, simulator_message, etc.', null=True),
        ),
    ]
