# Generated by Django 4.2.7 on 2026-01-14 04:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_simulationrun_metadata_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('brand_type', models.CharField(choices=[('heritage', 'Heritage'), ('indie', 'Indie'), ('mass', 'Mass'), ('prestige', 'Prestige'), ('luxury', 'Luxury')], max_length=50)),
                ('positioning_tags', models.JSONField(default=list, help_text='clean, clinical, performance, luxury heritage, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InnovationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('event_type', models.CharField(choices=[('launch', 'Product Launch'), ('reformulation', 'Reformulation'), ('campaign', 'Campaign'), ('collab', 'Collaboration'), ('channel_play', 'Channel Play')], max_length=50)),
                ('innovation_tags', models.JSONField(default=list, help_text='new claim, new format, bundle, channel play, etc.')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', 'market'],
            },
        ),
        migrations.CreateModel(
            name='InsightAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('json_output', models.JSONField(default=dict, help_text='Full structured JSON response')),
                ('confidence_score', models.IntegerField(blank=True, help_text='1-5 scale', null=True)),
                ('entropy_score', models.FloatField(blank=True, help_text='0-1 scale', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InsightQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('case_template', models.CharField(blank=True, max_length=50)),
                ('vertical', models.CharField(blank=True, max_length=20)),
                ('context', models.JSONField(default=dict, help_text='Selected markets/brands, filters, timeframe')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ManifoldPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_type', models.CharField(choices=[('market', 'Market'), ('brand', 'Brand'), ('product', 'Product')], max_length=20)),
                ('node_id', models.UUIDField(help_text='ID of the MarketDefinition, Brand, or Product')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('cluster_id', models.IntegerField(blank=True, null=True)),
                ('cluster_label', models.CharField(blank=True, max_length=200)),
                ('vertical', models.CharField(blank=True, max_length=20)),
                ('region', models.CharField(default='US', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['node_type', 'cluster_id'],
            },
        ),
        migrations.CreateModel(
            name='MarketDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('region', models.CharField(default='US', max_length=50)),
                ('vertical', models.CharField(choices=[('beauty', 'Beauty'), ('food', 'Food')], max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(blank=True, max_length=100)),
                ('price_tier', models.CharField(blank=True, choices=[('entry_premium', 'Entry Premium'), ('premium', 'Premium'), ('super_premium', 'Super-Premium'), ('ultra_luxury', 'Ultra-Luxury'), ('clinical', 'Clinical')], max_length=50)),
                ('channel_mix', models.JSONField(default=dict, help_text='Channel distribution: Sephora, Ulta, DTC, Amazon, etc.')),
                ('competitor_set', models.JSONField(default=list, help_text='List of Brand IDs')),
                ('tags', models.JSONField(default=list, help_text='Tags: clean, clinical, heritage, indie, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['vertical', 'category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_tier', models.CharField(blank=True, max_length=50)),
                ('claims', models.JSONField(default=list, help_text='hydration, barrier repair, anti-aging, brightening, etc.')),
                ('format', models.CharField(blank=True, max_length=100)),
                ('ingredients', models.JSONField(default=list, help_text='niacinamide, retinol, peptides, etc.')),
                ('launch_date', models.DateField(blank=True, null=True)),
                ('channel', models.CharField(blank=True, max_length=100)),
                ('is_bundle', models.BooleanField(default=False)),
                ('is_kit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.brand')),
            ],
            options={
                'ordering': ['-launch_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MarketSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('intent_index', models.FloatField(blank=True, help_text='Proxy for consumer intent', null=True)),
                ('price_elasticity_proxy', models.FloatField(blank=True, null=True)),
                ('trend_momentum', models.FloatField(blank=True, null=True)),
                ('social_velocity', models.FloatField(blank=True, null=True)),
                ('search_share_proxy', models.FloatField(blank=True, null=True)),
                ('review_sentiment_proxy', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='api.marketdefinition')),
            ],
            options={
                'ordering': ['-date', 'market'],
            },
        ),
        migrations.AddIndex(
            model_name='marketdefinition',
            index=models.Index(fields=['vertical', 'region'], name='api_marketd_vertica_6d99f0_idx'),
        ),
        migrations.AddIndex(
            model_name='marketdefinition',
            index=models.Index(fields=['category', 'sub_category'], name='api_marketd_categor_0dc1c2_idx'),
        ),
        migrations.AddIndex(
            model_name='marketdefinition',
            index=models.Index(fields=['price_tier'], name='api_marketd_price_t_afa930_idx'),
        ),
        migrations.AddIndex(
            model_name='manifoldpoint',
            index=models.Index(fields=['node_type', 'node_id'], name='api_manifol_node_ty_8b00d4_idx'),
        ),
        migrations.AddIndex(
            model_name='manifoldpoint',
            index=models.Index(fields=['vertical', 'region'], name='api_manifol_vertica_5e3d14_idx'),
        ),
        migrations.AddIndex(
            model_name='manifoldpoint',
            index=models.Index(fields=['cluster_id'], name='api_manifol_cluster_7fe22e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='manifoldpoint',
            unique_together={('node_type', 'node_id', 'vertical', 'region')},
        ),
        migrations.AddIndex(
            model_name='insightquery',
            index=models.Index(fields=['case_template', 'vertical'], name='api_insight_case_te_c3afc9_idx'),
        ),
        migrations.AddIndex(
            model_name='insightquery',
            index=models.Index(fields=['timestamp'], name='api_insight_timesta_cad035_idx'),
        ),
        migrations.AddField(
            model_name='insightanswer',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.insightquery'),
        ),
        migrations.AddField(
            model_name='innovationevent',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='innovation_events', to='api.brand'),
        ),
        migrations.AddField(
            model_name='innovationevent',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innovation_events', to='api.marketdefinition'),
        ),
        migrations.AddField(
            model_name='innovationevent',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='innovation_events', to='api.product'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['brand_type'], name='api_brand_brand_t_f8685b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand', 'category'], name='api_product_brand_i_9e1299_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price_tier'], name='api_product_price_t_874131_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['launch_date'], name='api_product_launch__85d361_idx'),
        ),
        migrations.AddIndex(
            model_name='marketsignal',
            index=models.Index(fields=['market', 'date'], name='api_markets_market__864cca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='marketsignal',
            unique_together={('market', 'date')},
        ),
        migrations.AddIndex(
            model_name='innovationevent',
            index=models.Index(fields=['market', 'date'], name='api_innovat_market__2e8f5f_idx'),
        ),
        migrations.AddIndex(
            model_name='innovationevent',
            index=models.Index(fields=['brand', 'date'], name='api_innovat_brand_i_50f6b2_idx'),
        ),
        migrations.AddIndex(
            model_name='innovationevent',
            index=models.Index(fields=['event_type'], name='api_innovat_event_t_c8657e_idx'),
        ),
    ]
