# Generated by Django 4.2.7 on 2026-01-14 04:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_brand_innovationevent_insightanswer_insightquery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifoldpoint',
            name='reactivity_score',
            field=models.FloatField(blank=True, help_text='Impact score from last simulation (0-1)', null=True),
        ),
        migrations.AddField(
            model_name='manifoldpoint',
            name='z',
            field=models.FloatField(default=0.0, help_text='Z coordinate for 3D manifold'),
        ),
        migrations.CreateModel(
            name='MarketSimRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('vertical', models.CharField(max_length=20)),
                ('region', models.CharField(default='US', max_length=50)),
                ('scenario_params', models.JSONField(default=dict, help_text='Price tier, channel, claim emphasis, etc.')),
                ('filters', models.JSONField(default=dict, help_text='Selected markets, categories, etc.')),
                ('pinned_nodes', models.JSONField(default=list, help_text='List of pinned node IDs')),
                ('seed', models.IntegerField(default=42, help_text='Random seed for reproducibility')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vertical', 'region'], name='api_markets_vertica_37a4af_idx'), models.Index(fields=['created_at'], name='api_markets_created_53c4e3_idx')],
            },
        ),
        migrations.CreateModel(
            name='MarketSimResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('impacted_clusters', models.JSONField(default=list, help_text='List of impacted clusters with scores')),
                ('impacted_points', models.JSONField(default=list, help_text='Points with reactivity scores')),
                ('category_tier_shifts', models.JSONField(default=dict, help_text='Category × tier impact table')),
                ('competitor_positioning', models.JSONField(default=dict, help_text='Competitor positioning grid')),
                ('innovation_patterns', models.JSONField(default=dict, help_text='Innovation patterns')),
                ('confidence_score', models.IntegerField(help_text='1-5 scale')),
                ('entropy_score', models.FloatField(help_text='0-1 scale')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sim_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.marketsimrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketInsightAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('json_output', models.JSONField(default=dict, help_text='Strict JSON schema output')),
                ('gpt_model', models.CharField(default='gpt-4o', max_length=50)),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('cached', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sim_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='api.marketsimresult')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
