# Generated by Django 4.2.7 on 2025-12-19 02:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceSurveyDatum',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dataset_name', models.CharField(default='Fast-Food Consumer Survey 2024', max_length=100)),
                ('date', models.DateField()),
                ('region', models.CharField(max_length=50)),
                ('archetype', models.CharField(blank=True, max_length=50)),
                ('question_text', models.TextField()),
                ('distribution_json', models.JSONField(default=dict, help_text='Response distribution')),
                ('snippet_text', models.TextField(help_text='Short respondent quote')),
                ('metadata_json', models.JSONField(default=dict, help_text='Sample size, confidence, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HypothesisRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('input_text', models.TextField()),
                ('filters_json', models.JSONField(default=dict)),
                ('agent_count', models.IntegerField(default=100)),
                ('mode', models.CharField(choices=[('gpt', 'GPT'), ('mock', 'Mock')], default='mock', max_length=10)),
                ('aggregated_result_json', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonaAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=100)),
                ('age_bucket', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('income', models.CharField(max_length=50)),
                ('archetype', models.CharField(choices=[('value_seeker', 'Value Seeker'), ('health_optimizer', 'Health Optimizer'), ('convenience_loyalist', 'Convenience Loyalist'), ('late_night_craver', 'Late-night Craver'), ('trend_chaser', 'Trend Chaser'), ('family_bundle_buyer', 'Family Bundle Buyer'), ('protein_maximizer', 'Protein Maximizer')], max_length=50)),
                ('taste_profile_json', models.JSONField(default=list, help_text='Taste preferences as tags/vector')),
                ('behavior_params_json', models.JSONField(default=dict, help_text='Behavioral parameters: price_sensitivity, health_bias, brand_loyalty, novelty_seeking')),
                ('system_prompt', models.TextField(help_text='GPT system prompt for this persona')),
                ('biography', models.TextField(blank=True, help_text='Short persona biography')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('likert', 'Likert Scale'), ('multiple_choice', 'Multiple Choice'), ('open', 'Open Ended')], max_length=20)),
                ('choices_json', models.JSONField(default=list, help_text='Choices for multiple choice or Likert scale')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_id', models.UUIDField()),
                ('response_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='api.personaagent')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.surveyquestion')),
            ],
        ),
        migrations.AddIndex(
            model_name='personaagent',
            index=models.Index(fields=['age_bucket', 'gender', 'region', 'income', 'archetype'], name='api_persona_age_buc_4347d3_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencesurveydatum',
            index=models.Index(fields=['region', 'archetype'], name='api_evidenc_region_49ec92_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['run_id', 'agent', 'question'], name='api_surveyr_run_id_4b6e92_idx'),
        ),
    ]
